### ISSUE TITLE
New Basketball formulas

### ISSUE THREAD

**Issue by blackmage37** [NS-Sports/Xkoranate-CE#10]
Suggested: 
https://forum.nationstates.net/viewtopic.php?p=36554365#p36554365 
https://forum.nationstates.net/viewtopic.php?p=36554511#p36554511

Banija and Baker Park have suggested creating basketball formulas that support home field advantage and appropriate formulas for different rule sets. The current basketball formula is roughly appropriate for FIBA or NCAA rules but is way too low scoring to simulate NBA rules.

This may be doable through new sports files but adding new paradigms is also an option.

**Comment by kalactin** [comment]
The necessary file can be found here
https://github.com/kalactin/Xkoranate-CE/blob/kalactin-patch-1-1/sports/basketball/basketball_nbascoring.xml

**Comment by blackmage37** [comment]
addressed in https://github.com/NS-Sports/Xkoranate-CE/pull/14
